title = "Office 365 Account Management RESTful API"

[microsoft]
domain = "http://yourdoamin"
authorize_url = "https://login.microsoftonline.com/common/oauth2/v2.0/authorize"
token_url = "https://login.microsoftonline.com/common/oauth2/v2.0/token"
client_id = "your microsoft client id"
client_secret = "your microsoft client secret"
tenant_id = "your tenant id"
scope = "offline_access User.ReadWrite.All Directory.ReadWrite.All Directory.AccessAsUser.All"

[app]
listen_addr = ":8088"
access_key = "api gateway access key"
access_secret = "api getway access secret"
