name: Go
on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: go build -ldflags "-s -w" -v -o dist/webapi main.go
     
    - name: Deploy
      run: |
        mkdir "$HOME/.ssh"
        echo ${{ secrets.SSH_PRIVATE_KEY }} > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
        ls -al $HOME/.ssh
        rsync -Pav -e "ssh -o StrictHostKeyChecking=no" dist app@${{ secrets.HOST_IP }}:/srv/web/office365

